prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?term WHERE 
{
  {?term <http://www.geneontology.org/formats/oboInOwl#inSubset> ?subset .}
  FILTER((STR(?subset)="lethal_phase") && isIRI(?term) && (regex(str(?term), UCASE("dpo_")) || regex(str(?term), "http://purl.obolibrary.org/obo/FBcv_") || regex(str(?term), "http://purl.obolibrary.org/obo/fbcv_")))
}
