contact: null
contributors: null
creators: null
description: None
dosdp_tools_options: --obo-prefixes=true --restrict-axioms-to=logical
edit_format: owl
export_formats:
- owl
- obo
- json
github_org: FlyBase
gzip_main: false
id: dpo
import_group:
  directory: imports/
  disabled: false
  ids: null
  products:
  - description: null
    id: fbdv
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: fbbt
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: go
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: ro
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: chebi
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: pato
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  rebuild_if_source_changes: true
import_pattern_ontology: false
license: Unspecified
namespaces:
- http://purl.obolibrary.org/obo/FBcv_
obo_format_options: ''
pattern_group: null
pattern_pipelines_group: null
primary_release: simple-non-classified
reasoner: ELK
release_artefacts:
- base
- simple
- non-classified
- full
repo: flybase-controlled-vocabulary
report_fail_on: none
robot_java_args: ''
robot_settings: null
robot_version: null
robotemplate_group: null
subset_group: null
title: FlyBase Controlled Vocabulary
travis_emails: null
uribase: http://purl.obolibrary.org/obo
use_dosdps: true
